"""Crisis forecast models for the memoir project.

Defines enumerations and data structures used to represent risk
forecasts — predictions about potential future problems derived from
patterns observed in git history.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any, Dict, List, Optional


class RiskType(Enum):
    """Classification of forecastable risk categories.

    Each value represents a distinct kind of project health risk that
    can be predicted from historical commit patterns.
    """

    BURNOUT = "burnout"
    TECHNICAL_DEBT_CRISIS = "technical_debt_crisis"
    BUS_FACTOR = "bus_factor"
    MAINTAINABILITY = "maintainability"
    STAGNATION = "stagnation"


class RiskLevel(Enum):
    """Overall risk severity level for a forecast.

    Ranges from LOW (negligible concern) to CRITICAL (imminent threat).
    """

    LOW = "low"
    MODERATE = "moderate"
    HIGH = "high"
    CRITICAL = "critical"


@dataclass
class ForecastIndicator:
    """A single measurable indicator that contributes to a risk forecast.

    Indicators are quantitative signals whose current value, trend, and
    threshold define whether a risk is materialising.

    Attributes:
        name: Human-readable name of the indicator.
        current_value: The most recently observed value.
        threshold_value: The value at which the indicator becomes concerning.
        trend: Direction of change — "rising", "stable", or "declining".
        description: Explanation of what this indicator measures.
    """

    name: str
    current_value: float
    threshold_value: float
    trend: str
    description: str

    def to_dict(self) -> Dict[str, Any]:
        """Serialize the indicator to a JSON-compatible dictionary.

        Returns:
            A dictionary representation of this indicator.
        """
        return {
            "name": self.name,
            "current_value": self.current_value,
            "threshold_value": self.threshold_value,
            "trend": self.trend,
            "description": self.description,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> ForecastIndicator:
        """Deserialize an indicator from a dictionary.

        Args:
            data: A dictionary, typically produced by ``to_dict``.

        Returns:
            A new ``ForecastIndicator`` instance.
        """
        return cls(
            name=data["name"],
            current_value=float(data["current_value"]),
            threshold_value=float(data["threshold_value"]),
            trend=data["trend"],
            description=data["description"],
        )


@dataclass
class Forecast:
    """A risk forecast predicting a potential future project crisis.

    Forecasts are generated by the analysis engine based on detected
    patterns and trend indicators.  Each forecast describes a risk,
    quantifies its likelihood, and provides an actionable recommendation.

    Attributes:
        id: Unique identifier for this forecast.
        risk_type: The category of risk being forecast.
        risk_level: Overall severity level of the predicted risk.
        title: Human-readable short title.
        description: Detailed explanation of the forecast risk.
        indicators: Quantitative indicators supporting this forecast.
        probability: Estimated probability from 0.0 (impossible) to 1.0 (certain).
        estimated_timeline: Rough time window until the risk materialises (e.g. "2-4 weeks").
        recommendation: Suggested action to mitigate or monitor the risk.
        historical_precedent: Optional reference to a similar past event.
    """

    id: str
    risk_type: RiskType
    risk_level: RiskLevel
    title: str
    description: str
    indicators: List[ForecastIndicator]
    probability: float
    estimated_timeline: str
    recommendation: str
    historical_precedent: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """Serialize the forecast to a JSON-compatible dictionary.

        Enums are stored by their value.  Nested indicators are
        recursively serialized.

        Returns:
            A dictionary representation of this forecast.
        """
        return {
            "id": self.id,
            "risk_type": self.risk_type.value,
            "risk_level": self.risk_level.value,
            "title": self.title,
            "description": self.description,
            "indicators": [ind.to_dict() for ind in self.indicators],
            "probability": self.probability,
            "estimated_timeline": self.estimated_timeline,
            "recommendation": self.recommendation,
            "historical_precedent": self.historical_precedent,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> Forecast:
        """Deserialize a forecast from a dictionary.

        Nested indicator dictionaries are recursively reconstructed
        using ``ForecastIndicator.from_dict``.

        Args:
            data: A dictionary, typically produced by ``to_dict``.

        Returns:
            A new ``Forecast`` instance.
        """
        indicators = [
            ForecastIndicator.from_dict(ind)
            for ind in data.get("indicators", [])
        ]

        return cls(
            id=data["id"],
            risk_type=RiskType(data["risk_type"]),
            risk_level=RiskLevel(data["risk_level"]),
            title=data["title"],
            description=data["description"],
            indicators=indicators,
            probability=float(data["probability"]),
            estimated_timeline=data["estimated_timeline"],
            recommendation=data["recommendation"],
            historical_precedent=data.get("historical_precedent"),
        )
